// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initBigNumbers
void initBigNumbers(int bitsPrecision);
RcppExport SEXP _TruncatedSamplingSpeedup_initBigNumbers(SEXP bitsPrecisionSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type bitsPrecision(bitsPrecisionSEXP);
    initBigNumbers(bitsPrecision);
    return R_NilValue;
END_RCPP
}
// truncatedSamplingSubiteration
double truncatedSamplingSubiteration(double uniformSample0, double uniformSample1, double minusZi, double Lo, double ai, bool thereIsAHigherBound, double theHigherBound);
RcppExport SEXP _TruncatedSamplingSpeedup_truncatedSamplingSubiteration(SEXP uniformSample0SEXP, SEXP uniformSample1SEXP, SEXP minusZiSEXP, SEXP LoSEXP, SEXP aiSEXP, SEXP thereIsAHigherBoundSEXP, SEXP theHigherBoundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type uniformSample0(uniformSample0SEXP);
    Rcpp::traits::input_parameter< double >::type uniformSample1(uniformSample1SEXP);
    Rcpp::traits::input_parameter< double >::type minusZi(minusZiSEXP);
    Rcpp::traits::input_parameter< double >::type Lo(LoSEXP);
    Rcpp::traits::input_parameter< double >::type ai(aiSEXP);
    Rcpp::traits::input_parameter< bool >::type thereIsAHigherBound(thereIsAHigherBoundSEXP);
    Rcpp::traits::input_parameter< double >::type theHigherBound(theHigherBoundSEXP);
    rcpp_result_gen = Rcpp::wrap(truncatedSamplingSubiteration(uniformSample0, uniformSample1, minusZi, Lo, ai, thereIsAHigherBound, theHigherBound));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TruncatedSamplingSpeedup_initBigNumbers", (DL_FUNC) &_TruncatedSamplingSpeedup_initBigNumbers, 1},
    {"_TruncatedSamplingSpeedup_truncatedSamplingSubiteration", (DL_FUNC) &_TruncatedSamplingSpeedup_truncatedSamplingSubiteration, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_TruncatedSamplingSpeedup(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
