# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initBigNumbers <- function(bitsPrecision) {
    invisible(.Call(`_TruncatedSamplingSpeedup_initBigNumbers`, bitsPrecision))
}

truncatedSamplingSubiteration <- function(uniformSample0, uniformSample1, minusZi, Lo, ai, thereIsAHigherBound, theHigherBound) {
    .Call(`_TruncatedSamplingSpeedup_truncatedSamplingSubiteration`, uniformSample0, uniformSample1, minusZi, Lo, ai, thereIsAHigherBound, theHigherBound)
}

